### ISSUE TITLE
Publish fat APK in GitHub releases?

### ISSUE THREAD

**Issue by bartekpacia** [EmergeTools/hackernews#140]
Hey 👋 thanks for open-sourcing this project! Love it.

It'd be cool if we could download fat APKs directly from GitHub releases.

(Same goes for the iOS simulator builds when the iOS app becomes available)

**Comment by rbro112** [comment]
Thanks for the suggestion! We'll discuss as a team and let you know if we decide to do so.

Nonetheless, cloning the project currently and building should allow you to generate the full APK yourself for the time being (`./gradlew :app:assembleRelease` should do the trick).

**Comment by bartekpacia** [comment]
Hey, no need to discuss:D I did it in #148. I'll be grateful for a review.

**Comment by rbro112** [comment]
Thanks @bartekpacia! Will review shortly and let you know of any feedback.
